<a href="https://colab.research.google.com/github/ruforavishnu/Project_Simulations/blob/main/12th_standard_Maths_Chapter3_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
A = np.array([[2,3],
             [1,4]])


B = np.array([[5,2],
             [0,7]])



In [6]:
print('Matrix A: \n', A)
print('\n\nMatrix B: \n', B)

Matrix A: 
 [[2 3]
 [1 4]]


Matrix B: 
 [[5 2]
 [0 7]]


Basic Matrix Operations

In [7]:
print('A + B: \n', A + B)

A + B: 
 [[ 7  5]
 [ 1 11]]


In [8]:
print('A - B: \n', A - B)

A - B: 
 [[-3  1]
 [ 1 -3]]


In [9]:
print('A *3 (scalar multiplication): \n', 3* A)

A *3 (scalar multiplication): 
 [[ 6  9]
 [ 3 12]]


In [10]:
print('A *3 (scalar multiplication): \n', A*3)

A *3 (scalar multiplication): 
 [[ 6  9]
 [ 3 12]]


In [11]:
print('A dot B (matrix multiplication): \n', np.dot(A,B))

A dot B (matrix multiplication): 
 [[10 25]
 [ 5 30]]


Transpose, Determinant, Inverse

In [12]:
print('Transpose of A: \n', A.T)

Transpose of A: 
 [[2 1]
 [3 4]]


In [13]:
det_A = np.linalg.det(A)
print('Determinant of A: ', det_A)

Determinant of A:  5.000000000000001


In [14]:
if det_A != 0:
  inv_A = np.linalg.inv(A)
  print('Inverse of A: \n', inv_A)
else:
  print('A is not invertible')

Inverse of A: 
 [[ 0.8 -0.6]
 [-0.2  0.4]]


Solve a System of Equations

2x + 3y = 8


x + 4y = 7

In [17]:
coeff = np.array([[2,3],
                  [1,4]])

rhs = np.array([8,7])

solution = np.linalg.solve(coeff, rhs)
print('Solution for [x,y]: ', solution)



Solution for [x,y]:  [2.2 1.2]
